/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoJpaController;
import controller.ProfessorJpaController;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Professor;
import persistence.PersistenceSingleton;

/**
 *
 * @author alunos
 */
public class CadastroP extends javax.swing.JFrame {

    /**
     * Creates new form CadastroP
     */
    public CadastroP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputNomeP = new javax.swing.JTextField();
        inputEmailP = new javax.swing.JTextField();
        inputSenhaP = new javax.swing.JTextField();
        inputConfSenhaP = new javax.swing.JTextField();
        inputLoginP = new javax.swing.JTextField();
        buttonConfirmaP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        inputDis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTIVITIES ORGANIZER");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACTIVITIES ORGANIZER");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACTIVITIES ORGANIZER");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CADASTRO");

        jLabel5.setText("Login:");

        jLabel6.setText("Senha:");

        jLabel7.setText("Confirma senha:");

        jLabel8.setText("Nome:");

        jLabel9.setText("Email:");

        inputNomeP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNomePFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNomePFocusLost(evt);
            }
        });
        inputNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomePActionPerformed(evt);
            }
        });

        inputEmailP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailPFocusLost(evt);
            }
        });
        inputEmailP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailPActionPerformed(evt);
            }
        });

        inputSenhaP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputSenhaPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSenhaPFocusLost(evt);
            }
        });
        inputSenhaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaPActionPerformed(evt);
            }
        });

        inputConfSenhaP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputConfSenhaPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputConfSenhaPFocusLost(evt);
            }
        });
        inputConfSenhaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConfSenhaPActionPerformed(evt);
            }
        });

        inputLoginP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputLoginPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputLoginPFocusLost(evt);
            }
        });
        inputLoginP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoginPActionPerformed(evt);
            }
        });

        buttonConfirmaP.setText("Confirma");
        buttonConfirmaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmaPActionPerformed(evt);
            }
        });

        jLabel10.setText("Disciplina que ministra");

        inputDis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputDisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputDisFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonConfirmaP)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputConfSenhaP, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                            .addComponent(inputDis)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputSenhaP, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputLoginP, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputLoginP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputSenhaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputConfSenhaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonConfirmaP)
                .addGap(72, 72, 72))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomePActionPerformed

    private void inputEmailPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailPActionPerformed

    private void inputSenhaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaPActionPerformed

    private void inputConfSenhaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConfSenhaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConfSenhaPActionPerformed

    private void inputLoginPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoginPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginPActionPerformed

    private void buttonConfirmaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmaPActionPerformed
// TODO add your handling code here:
        if (((inputNomeP.getText()).equals("")) || ((inputLoginP.getText()).equals("")) || ((inputSenhaP.getText()).equals("")) || ((inputConfSenhaP.getText()).equals("")) || ((inputEmailP.getText()).equals("")) || ((inputDis.getText()).equals(""))){
            JOptionPane.showMessageDialog(this, "Todos os campos são de preenchimento obrigatório!");
        } else {
            if (!(inputSenhaP.getText()).equals(inputConfSenhaP.getText())){
               JOptionPane.showMessageDialog(this, "As senhas não correspondem!");
            }else{
                 EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();    
                 System.out.println(ponte);
                 ProfessorJpaController pController = new ProfessorJpaController(ponte);
                 Professor p1 = new Professor();
                 p1.setNomeP((inputNomeP.getText()));
                 p1.setLoginP((inputLoginP.getText()));
                 p1.setSenhaP((inputSenhaP.getText()));
                 p1.setEmailP((inputEmailP.getText())); 
                 p1.setDis((inputDis.getText())); 
                 
                 pController.create(p1);
                 System.out.println(p1.toString());
            }
        }
        TelaPrincipalAluno iniciar = new TelaPrincipalAluno();
        iniciar.setVisible(true);
        iniciar.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonConfirmaPActionPerformed

    private void inputNomePFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNomePFocusLost
        // TODO add your handling code here:
        if(inputNomeP.getText().equals("NomeP")){
            inputNomeP.setText("");
        }
    }//GEN-LAST:event_inputNomePFocusLost

    private void inputNomePFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNomePFocusGained
        // TODO add your handling code here:
        inputNomeP.setText("");
    }//GEN-LAST:event_inputNomePFocusGained

    private void inputEmailPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailPFocusLost
        // TODO add your handling code here:
        if(inputEmailP.getText().equals("EmailP")){
            inputEmailP.setText("");
        }
    }//GEN-LAST:event_inputEmailPFocusLost

    private void inputEmailPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailPFocusGained
        // TODO add your handling code here:
        inputEmailP.setText("");
    }//GEN-LAST:event_inputEmailPFocusGained

    private void inputLoginPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputLoginPFocusLost
        // TODO add your handling code here:
        if(inputLoginP.getText().equals("LoginP")){
            inputLoginP.setText("");
        }
    }//GEN-LAST:event_inputLoginPFocusLost

    private void inputLoginPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputLoginPFocusGained
        // TODO add your handling code here:
        inputLoginP.setText("");
    }//GEN-LAST:event_inputLoginPFocusGained

    private void inputSenhaPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSenhaPFocusLost
        // TODO add your handling code here:
        if(inputSenhaP.getText().equals("SenhaP")){
            inputSenhaP.setText("");
        }
    }//GEN-LAST:event_inputSenhaPFocusLost

    private void inputSenhaPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSenhaPFocusGained
        // TODO add your handling code here:
         inputSenhaP.setText("");
    }//GEN-LAST:event_inputSenhaPFocusGained

    private void inputConfSenhaPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfSenhaPFocusLost
        // TODO add your handling code here:
        if(inputConfSenhaP.getText().equals("ConfSenhaP")){
            inputConfSenhaP.setText("");
        }
    }//GEN-LAST:event_inputConfSenhaPFocusLost

    private void inputConfSenhaPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfSenhaPFocusGained
        // TODO add your handling code here:
        inputConfSenhaP.setText("");
    }//GEN-LAST:event_inputConfSenhaPFocusGained

    private void inputDisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDisFocusLost
        // TODO add your handling code here:
        if(inputDis.getText().equals("Dis")){
            inputDis.setText("");
        }
    }//GEN-LAST:event_inputDisFocusLost

    private void inputDisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDisFocusGained
        // TODO add your handling code here:
        inputDis.setText("");
    }//GEN-LAST:event_inputDisFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmaP;
    private javax.swing.JTextField inputConfSenhaP;
    private javax.swing.JTextField inputDis;
    private javax.swing.JTextField inputEmailP;
    private javax.swing.JTextField inputLoginP;
    private javax.swing.JTextField inputNomeP;
    private javax.swing.JTextField inputSenhaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
